const Routes = {
  HOME: '/',
  ABOUT_US: '/about-us',
  MISSION: '/mass-centers',
  ABUJA_MISSION: '/mass-centers/abuja',
  ALIFOKPA_MISSION: '/mass-centers/alifokpa',
  BENUE_MISSION: '/mass-centers/benue',
  BODE_MISSION: '/mass-centers/bode',
  CALABAR_MISSION: '/mass-centers/calabar',
  LAGOS_MISSION: '/mass-centers/lagos',
  ONITSHA_MISSION: '/mass-centers/onitsha',
  OWERRI_MISSION: '/mass-centers/owerri',
  PORT_HARCOURT_MISSION: '/mass-centers/port-harcourt',
  UMUNZE_MISSION: '/mass-centers/umunze',
  PRIESTS: '/priests',
  NKAMUKE_BEDE: '/priests/nkamuke-bede',
  OKERULU_JOHN: '/priests/okerulu-john',
  OJEKA_THOMAS: '/priests/ojeka-thomas',
};
export default Routes;
